CNI_ROOT=/net/redfox.ece.Virginia.EDU/isan0/users/nk9yx/cadence/synopsys;export CNI_ROOT
#CNI_DISPLAY_DIR=/net/redfox.ece.Virginia.EDU/isan0/users/nk9yx/cadence/synopsys/tech/cni130/santanaDisplay; export CNI_DISPLAY_DIR
CNI_PLAT_ROOT=${CNI_ROOT}/plat_linux_gcc483_64
PATH=${CNI_PLAT_ROOT}/3rd/bin:${CNI_PLAT_ROOT}/3rd/oa/bin/linux_rhel40_gcc483_64/opt:${CNI_PLAT_ROOT}/bin:${CNI_ROOT}/bin:${PATH};export PATH
CNI_LOG_DEFAULT=/dev/null;export CNI_LOG_DEFAULT
PYTHONHOME=${CNI_PLAT_ROOT}/3rd;export PYTHONHOME
PYTHONPATH=${CNI_ROOT}/pylib:${CNI_PLAT_ROOT}/pyext:${CNI_PLAT_ROOT}/lib:.:${PYTHONPATH};export PYTHONPATH
LD_LIBRARY_PATH=${CNI_PLAT_ROOT}/3rd/lib:${CNI_PLAT_ROOT}/3rd/oa/lib/linux_rhel40_gcc483_64/opt:${CNI_PLAT_ROOT}/lib:${LD_LIBRARY_PATH};export LD_LIBRARY_PATH
OA_PLUGIN_PATH=${CNI_PLAT_ROOT}/3rd/oa/data/plugins:${CNI_ROOT}/quickstart:${OA_PLUGIN_PATH};export OA_PLUGIN_PATH
